# Generated by Django 5.2.3 on 2025-10-10 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("category", "0001_initial"),
        ("subcategory", "0001_initial"),
        ("suppliers", "0002_alter_supplier_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="category.category",
                    ),
                ),
                (
                    "subcategory",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="subcategory.subcategory",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="suppliers.supplier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
                "indexes": [
                    models.Index(fields=["name"], name="product_pro_name_b60cd1_idx"),
                    models.Index(
                        fields=["category"], name="product_pro_categor_2b9d78_idx"
                    ),
                    models.Index(
                        fields=["subcategory"], name="product_pro_subcate_133485_idx"
                    ),
                    models.Index(
                        fields=["supplier"], name="product_pro_supplie_c098a5_idx"
                    ),
                ],
                "unique_together": {("name", "supplier")},
            },
        ),
    ]
