# Generated by Django 5.2.3 on 2025-10-13 12:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
        ("purchase", "0001_initial"),
        ("suppliers", "0002_alter_supplier_options_and_more"),
        ("warehouse", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="purchaseitem",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="purchaseorder",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RenameField(
            model_name="purchaseitem",
            old_name="purchase_order",
            new_name="purchase",
        ),
        migrations.RemoveField(
            model_name="purchaseorder",
            name="date",
        ),
        migrations.AddField(
            model_name="purchaseitem",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="purchaseitem",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="purchaseitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="product.product",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseitem",
            name="quantity",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="reference_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Received", "Received"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="purchase_orders",
                to="suppliers.supplier",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="warehouse",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="purchase_orders",
                to="warehouse.warehouse",
            ),
        ),
    ]
