# Generated by Django 5.2.3 on 2025-10-10 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suppliers", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="supplier",
            options={"verbose_name": "Supplier", "verbose_name_plural": "Suppliers"},
        ),
        migrations.AlterUniqueTogether(
            name="supplier",
            unique_together={("contact_email", "phone_number")},
        ),
        migrations.AddIndex(
            model_name="supplier",
            index=models.Index(fields=["name"], name="suppliers_s_name_6277a9_idx"),
        ),
        migrations.AddIndex(
            model_name="supplier",
            index=models.Index(
                fields=["contact_email"], name="suppliers_s_contact_6f86c4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supplier",
            index=models.Index(
                fields=["phone_number"], name="suppliers_s_phone_n_5ce1f5_idx"
            ),
        ),
    ]
