# Generated by Django 5.2.3 on 2025-10-17 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("product", "0001_initial"),
        ("warehouse", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ForecastResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("forecast_date", models.DateField(auto_now_add=True)),
                ("days_ahead", models.PositiveIntegerField(default=30)),
                ("predicted_sales", models.FloatField()),
                ("projected_stock", models.FloatField()),
                ("will_be_low", models.BooleanField(default=False)),
                ("forecast_series", models.JSONField(blank=True, null=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.product",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="warehouse.warehouse",
                    ),
                ),
            ],
            options={
                "ordering": ["-forecast_date"],
                "unique_together": {("product", "warehouse", "forecast_date")},
            },
        ),
    ]
